# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Elias Prince's Portfolio # This is what shows up in the tab of the browser

# Hero Section
name: Elias Prince
headline: Mechanical Engineer, NYC
description: >- # dont remove this line. this will ignore all new lines until the next section
  Mission driven engineer who is always excited to solve complex problems.
  Passionate about emerging technologies and leveraging engineering to improve the world around us.
  Currently focused on marine technology.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: assets/images/profile-image/EliasPicMed.jpeg

# Link your resume
# You can place your resume in assets/resume/{resume.pdf or add external link such as pdf saved in google drive 
resume-url: https://drive.google.com/file/d/13Z3duVzh-gguPU5r03oJVEE6rV9rd3DS/view?usp=sharing # or /assets/resume/resume.pdf

# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: eliasprince    # https://www.linkedin.com/in/eliasprince
  # github: EliasPrince    # https://github.com/EliasPrince

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Product Development
    tools:
    - Bubble
    - Miro
    - Airtable
    - Product Design Specification
    - Customer Discovery
  - category: Engineering
    tools:
    - Finite Element Analysis (FEA)
    - SolidWorks
    - SolidWorks Simulation
    - Nastram
    - FEMAP
    - VBA
    - Arduino
    - Python
  - category: Project Management
    tools:
    - Project Data Management (PDM)
    - Jira Agile Project Management
    - SQL

# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/{8-digit key}

# Active theme (Update this to switch themes). Make sure to keep the indentation the same.
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#A4BE5C"

#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
